# Generated by Django 5.1.3 on 2024-12-04 06:49

import ckeditor.fields
import django.contrib.auth.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('mainpage', '0002_category_subcategory_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Blog_name', models.CharField(max_length=100)),
                ('blorrer_image', models.ImageField(default=0, upload_to='productimages')),
                ('add_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('description', ckeditor.fields.RichTextField()),
            ],
        ),
        migrations.CreateModel(
            name='ExtendedUser',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('phone_no', models.CharField(default=0, max_length=12)),
                ('alt_no', models.CharField(default=0, max_length=12)),
                ('address', models.CharField(default=0, max_length=500)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_no', models.IntegerField(default=0)),
                ('customer_name', models.CharField(default=0, max_length=100)),
                ('customer_username', models.CharField(default=0, max_length=100)),
                ('phone', models.CharField(default=0, max_length=12)),
                ('email', models.CharField(default=0, max_length=100)),
                ('address', models.CharField(default=0, max_length=500)),
                ('Product_id', models.IntegerField(default=0)),
                ('product_img', models.ImageField(default=0, upload_to='productimages')),
                ('Product_quantity', models.IntegerField(default=1)),
                ('product_price', models.FloatField(default=0)),
                ('product_name', models.CharField(default=0, max_length=100)),
                ('status', models.BooleanField(default=False)),
                ('add_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('total_cost', models.FloatField(default=0)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainpage.extendeduser')),
                ('product_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainpage.product')),
            ],
        ),
    ]
