# Generated by Django 5.0.4 on 2024-12-11 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0004_about_compeny_cancelation_policy_privacy_policy_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('country', models.CharField(max_length=100)),
                ('scaffolding_type', models.CharField(max_length=100)),
                ('quantity', models.IntegerField()),
                ('product_finish', models.JSONField()),
            ],
        ),
    ]
